language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
script:
  - "cd react"
  - yarn
  - "cd packages/components"
  - yarn test
  - "cd ../store"
  - yarn test
  - "cd ../apps/navigator"
  - yarn test
  - yarn build
  - "cd ../navigator-context-api"
  - yarn test
  - yarn build
on:
  branch: master
