language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
matrix:
  include:
    - before_script:
        - "cd react"
        - yarn
        - "cd packages/apps/navigator"
      script:
        - yarn test
        - yarn build
    - before_script:
        - "cd react"
        - yarn
        - "cd packages/components"
      script:
        - yarn test
on:
  branch: master
