export const TOGGLE_SIDE_DRAWER = "TOGGLE_SIDE_DRAWER";

export const OAUTH_SET_RANDOM_STATE = "OAUTH_SET_RANDOM_STATE";
export const OAUTH_SET_DATA = "OAUTH_SET_DATA";
export const OAUTH_SHOW_AUTH_WINDOW = "OAUTH_SHOW_AUTH_WINDOW";

export const OAUTH_TOKEN_KEY_REQUEST = "OAUTH_TOKEN_KEY_REQUEST";
export const OAUTH_TOKEN_KEY_SUCCESS = "OAUTH_TOKEN_KEY_SUCCESS";
export const OAUTH_TOKEN_KEY_FAILURE = "OAUTH_TOKEN_KEY_FAILURE";

export const OAUTH_TOKEN_REQUEST = "OAUTH_TOKEN_REQUEST";
export const OAUTH_TOKEN_SUCCESS = "OAUTH_TOKEN_SUCCESS";
export const OAUTH_TOKEN_FAILURE = "OAUTH_TOKEN_FAILURE";

export const OAUTH_REVOKE_REFRESH_TOKEN_REQUEST = "REVOKE_REFRESH_TOKEN_REQUEST";
export const OAUTH_REVOKE_REFRESH_TOKEN_SUCCESS = "REVOKE_REFRESH_TOKEN_SUCCESS";
export const OAUTH_REVOKE_REFRESH_TOKEN_FAILURE = "REVOKE_REFRESH_TOKEN_FAILURE";
